[package]
name = "eth_proxy"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
ic-cdk = "0.3.1"
ic-cdk-macros = "0.3"
hex = "0.4.3"
ic-types = "0.1.3"
serde = "1.0.116"
ic-kit = "0.4.3"

[dependencies.num-bigint]
version = "0.4.2"